channels:
- conda-forge
dependencies:
- python=3.7
- pip:
  - azureml-core==1.27.0
  - azureml-defaults==1.27.0
  - joblib
  - azureml-sdk
  - pillow
  - tensorflow-gpu==1.15
  - numpy
  - joblib
  - gunicorn
  - flask
name: basic_env
