# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

# Azure Pipeline Template for Manual Validation of Models

parameters:
- name: businessOwnerEmail
  type: string
- name: instructionsText
  type: string


jobs:

- job: manual_validation_of_models
  displayName: 'Manual validation of ML models'
  pool: server 
  timeoutInMinutes: 4320 # job times out in 3 days
  steps:   
  - task: ManualValidation@0
    timeoutInMinutes: 4320 # task times out in 3 days
    inputs:
      notifyUsers: |
        ${{parameters.businessOwnerEmail}}
      instructions: ${{parameters.instructionsText}}
      onTimeout: 'reject'